### ISSUE TITLE
Failed to resolve Transmog 0.0.7 with SPM

### ISSUE THREAD

**Issue by Jeytery** [inket/Transmog#5]
Failed to resolve Transmog 0.0.7 with SPM

while installing the Transmog

**Comment by Jeytery** [comment]
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'

**Comment by inket** [comment]
Something is wrong with your Xcode setup. Please use Google

https://stackoverflow.com/questions/43418533/running-swift-build-in-terminal-leading-to-platform-path-errors
https://github.com/erlyaws/yaws/issues/389
https://github.com/onevcat/FengNiao/issues/13
